export const successful_login="successful_login";
// export const ADD_FLASH_MESSAGE  = 'ADD_FLASH_MESSAGE';
export const USER_LOGIN = 'USER_LOGIN';
export const UPDATE_MEAL = 'UPDATE_MEAL';
export const GET_MEALS = 'GET_MEALS';
export const DELETE_MEAL = 'DELETE_MEAL';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const ADD_MEAL = 'ADD_MEAL';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const SIGNUP_ADMIN = "SIGNUP_ADMIN";
export const GET_ORDER = "GET_ORDER"
